### ISSUE TITLE
This OTP release uses the unsupported Erlang NIF version "2.16".

### ISSUE THREAD

**Issue by ericlathrop** [rusterlium/rustler#374] opened 2021-08-11 20:13 UTC
I upgraded to the official `elixir:1.12.2` docker container, and now I'm getting this error when trying to run my app:

```
==> tds_encoding
Compiling NIF crate :tds_encoding (native/tds_encoding)...
   Compiling rustler_sys v2.0.0
   Compiling backtrace-sys v0.1.32
   Compiling syn v0.15.44
error: failed to run custom build command for `rustler_sys v2.0.0`

Caused by:
  process didn't exit successfully: `/code/elixir/_build/test/rustler_crates/tds_encoding/release/build/rustler_sys-a4e2cfcb3e502fa9/build-script-build` (exit status: 101)
  --- stdout
  This OTP release uses the unsupported Erlang NIF version "2.16".

  Please report at https://github.com/rustlerium/rustler.

  --- stderr
  thread 'main' panicked at 'gen_api.erl encountered an error.', /root/.cargo/registry/src/github.com-1ecc6299db9ec823/rustler_sys-2.0.0/build.rs:34:18
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
error: build failed
could not compile dependency :tds_encoding, "mix compile" failed. You can recompile this dependency with "mix deps.compile tds_encoding", update it with "mix deps.update tds_encoding" or clean it with "mix deps.clean tds_encoding"
** (RuntimeError) Rust NIF compile error (rustc exit code 101)
    (rustler 0.21.1) lib/mix/tasks/compile.rustler.ex:68: Mix.Tasks.Compile.Rustler.compile_crate/1
    (elixir 1.12.2) lib/enum.ex:1582: Enum."-map/2-lists^map/1-0-"/2
    (rustler 0.21.1) lib/mix/tasks/compile.rustler.ex:15: Mix.Tasks.Compile.Rustler.run/1
    (mix 1.12.2) lib/mix/task.ex:394: anonymous fn/3 in Mix.Task.run_task/3
    (mix 1.12.2) lib/mix/tasks/compile.all.ex:92: Mix.Tasks.Compile.All.run_compiler/2
    (mix 1.12.2) lib/mix/tasks/compile.all.ex:72: Mix.Tasks.Compile.All.compile/4
    (mix 1.12.2) lib/mix/tasks/compile.all.ex:59: Mix.Tasks.Compile.All.with_logger_app/2
    (mix 1.12.2) lib/mix/tasks/compile.all.ex:36: Mix.Tasks.Compile.All.run/1
```

My nif version:

```
# iex
Erlang/OTP 24 [erts-12.0.3] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [jit]

Interactive Elixir (1.12.2) - press Ctrl+C to exit (type h() ENTER for help)
iex(1)> :erlang.system_info(:nif_version)
'2.16'
```

I'm not real familiar with NIFs or the rust ecosystem, so apologies if I missed something.

**Comment by filmor** [comment] 2021-08-11 21:11
This is a duplicate of https://github.com/rusterlium/rustler/issues/359.

**Closed by filmor** 2021-08-11 21:11 UTC
