### ISSUE TITLE
Integrate cargo tests into Elixir test build. 

### ISSUE THREAD

**Issue by ghost** [rusterlium/rustler#147] opened 2018-06-06 05:48 UTC
It would be great if we could integrate cargo tests into the mix test task. If this is already there, pardon me but I have looked for docs.

**Comment by evnu** [comment] 2018-06-06 12:12
If this is not yet possible, would a new task `mix rustler.test` be something people here were interested in? This task would need to run `cargo test` for the crates defined in `:rustler_crates` (with an option to run only a specific crate). Using a separate Mix task, this could integrate with `mix test` by aliasing `test`:

```elixir
def project do
  [
  # ...
     aliases: [test: ["rustler.test", "test"]]
  ]
end
```

**Comment by kraythen** [comment] 2018-06-06 17:54
I would love that. Right now I have no way of testing my crates because I cant link without the erlang libs and I cant run tests in any other way.

**Comment by evnu** [comment] 2018-06-06 18:52
> Right now I have no way of testing my crates because I cant link without the erlang libs and I cant run tests in any other way.

So you want to use Rustler's types within `cargo test`? I stumbled over this problem [here](https://github.com/hansihe/rustler/issues/145) and it seems that this is not possible. However, this can be mitigated: The public API of your NIF can easily be tested from Elixir (see Rustler's own unit tests for example). That way, you can assert that the API works as intended. If you want to use fine-grained unit tests for functionality within the crate, `cargo test` can be used if you do not rely on NIF types. The latter works quite well for me now by avoiding to pull NIF types down into computation functions. For those functions, I use pure Rust types. Now, I run `cargo test` as part of my CI directly, and not from `mix test`. Chaining `cargo test` into `mix test` would be possible with a separate `mix rustler.test` task as proposed [here](https://github.com/hansihe/rustler/issues/147#issuecomment-395046924).

**Comment by evnu** [comment] 2018-06-06 19:40
I found a hacky way to run cargo tests from Elixir by using a trampoline function ([see](https://github.com/evnu/rusty/tree/test-trampoline) for a runnable example). Note that this might not work for more complicated Rustler types, maybe somebody with more knowledge on the internals and NIFs can add to this or explain that this solution cannot work.

```rust
rustler_export_nifs! {
    "Elixir.Rusty",
    [
        ("trampoline", 1, trampoline)
    ],
    None
}

fn trampoline<'a>(env: NifEnv<'a>, args: &[NifTerm<'a>]) -> NifResult<NifTerm<'a>> {
    let ident: String = args[0].decode()?;

    match ident.as_ref() {
        "test::test()" => test::test(),
        "test::test2()" => test::test2(),
        &_ => {
            let error = NifError::RaiseTerm(Box::new(format!("Unknown test case {}", ident)));
            return Err(error);
        }
    }

    Ok(atoms::ok().encode(env))
}

mod test {
    use super::*;

    pub fn test() {
        assert_eq!(true, false);
    }

    pub fn test2() {
        assert_eq!(atoms::ok(), atoms::ok());
    }
}
```

Now, `trampoline` can be used from Elixir to call into the test functions:

```elixir
  test "failing test" do
    assert :ok == trampoline("test::test()")
  end

  test "working test" do
    assert :ok == trampoline("test::test2()")
  end
```

Alas, the test functions and trampoline are always present in the resulting library. This could be fixed by making the trampoline compile only if `#[cfg(test)]` and replace it with a dummy otherwise. Then, the `mod test` should also be marked as such. To make that work, we would need to allow adding the test feature to the cargo build call in `compile.rustler.ex`.

**Comment by scrogson** [comment] 2018-06-06 20:45
What would `cargo test` actually give you? NIF functions need to be called by the BEAM. So the best way is to just write tests in Elixir and test that your NIF works as expected.

**Comment by kraythen** [comment] 2018-06-07 00:33
There are functions in the NIF that are not called directly by elixir and I hardly think I need to go through the merits of unit testing? I think if the mix plugin could just run `cargo test` then it would be great.

**Comment by scrogson** [comment] 2018-06-07 01:30
@kraythen I see. That seems like a nice addition. 👍

**Comment by kraythen** [comment] 2018-06-09 16:27
Yep, as it is now I can create a cargo workspace and separate nif code from the actual implementations but that limits testability of course.

**Comment by evnu** [comment] 2018-11-29 13:41
I recently put some more thought into unit testing rust crates directly in combination with Rustler. Another approach to do that is to use feature flags, e.g. only compile Serializers/Deserializers if a specific feature is activated. That way, one can still write unit tests for `cargo test` as usual. Maybe somebody reading this can make use of that idea.

**Comment by evnu** [comment] 2021-06-23 11:37
Closing, there hasn't been activity here in a long time and it is not yet clear how to proceed. Feel free to reopen if this changes!

**Closed by evnu** 2021-06-23 11:37 UTC
